<?php


namespace app\admin\business;
use app\admin\model\AdminRole as AdminRoleModel;

class AdminRole extends BaseBus
{
    public function __construct()
    {
        $this->model = new AdminRoleModel();
    }

    // 批量删除，重写
    public function delByIds($ids)
    {
        // 默认角色不能删除
        if (strpos($ids, ',') != false) {
            $ids = explode(',', $ids);
            if (in_array('1', $ids)) {
                return [];
            }
        }else{
            if ($ids == '1') {
                return [];
            }
        }
        return parent::delByIds($ids); // TODO: Change the autogenerated stub
    }

    // 单条删除，重写
    public function delById($id)
    {
        // 默认角色不能删除
        if ($id == '1') {
            return [];
        }
        return parent::delById($id); // TODO: Change the autogenerated stub
    }
}